INSERT INTO `partier`(`parti`, `partikode`) VALUES ('Blankt', 'Blankt');
INSERT INTO `partier`(`parti`, `partikode`) VALUES ('Alliansen - Alternativ for Norge', 'AAN');
INSERT INTO `partier`(`parti`, `partikode`) VALUES ('Arbeiderpartiet', 'A');
INSERT INTO `partier`(`parti`, `partikode`) VALUES ('Demokratene', 'DEMN');
INSERT INTO `partier`(`parti`, `partikode`) VALUES ('Feministisk Initiativ', 'FI');
INSERT INTO `partier`(`parti`, `partikode`) VALUES ('Folkeaksjonen Nei til mer bompenger', 'FNB');
INSERT INTO `partier`(`parti`, `partikode`) VALUES ('Fremskrittspartiet', 'FRP');
INSERT INTO `partier`(`parti`, `partikode`) VALUES ('Generasjonspartiet', 'GENE');
INSERT INTO `partier`(`parti`, `partikode`) VALUES ('Høyre', 'H');
INSERT INTO `partier`(`parti`, `partikode`) VALUES ('Helsepartiet', 'HELSE');
INSERT INTO `partier`(`parti`, `partikode`) VALUES ('Industri- og Næringspartiet', 'INP');
INSERT INTO `partier`(`parti`, `partikode`) VALUES ('Kristelig Folkeparti', 'KRF');
INSERT INTO `partier`(`parti`, `partikode`) VALUES ('Kystpartiet', 'KYST');
INSERT INTO `partier`(`parti`, `partikode`) VALUES ('Liberalistene', 'LIBS');
INSERT INTO `partier`(`parti`, `partikode`) VALUES ('Miløpartiet De Grønne', 'MDG');
INSERT INTO `partier`(`parti`, `partikode`) VALUES ('Norges Kommunistiske Parti', 'NKP');
INSERT INTO `partier`(`parti`, `partikode`) VALUES ('Partiet De Kristne', 'KRISTNE');
INSERT INTO `partier`(`parti`, `partikode`) VALUES ('Partiet Sentrum', 'PS');
INSERT INTO `partier`(`parti`, `partikode`) VALUES ('Pasientfokus', 'PF');
INSERT INTO `partier`(`parti`, `partikode`) VALUES ('Pensjonistpartiet', 'PP');
INSERT INTO `partier`(`parti`, `partikode`) VALUES ('Piratpartiet', 'PIR');
INSERT INTO `partier`(`parti`, `partikode`) VALUES ('Rødt', 'RØDT');
INSERT INTO `partier`(`parti`, `partikode`) VALUES ('Redd Naturen', 'RN');
INSERT INTO `partier`(`parti`, `partikode`) VALUES ('Senterpartiet', 'SP');
INSERT INTO `partier`(`parti`, `partikode`) VALUES ('SV - Sosialistisk Venstreparti', 'SV');
INSERT INTO `partier`(`parti`, `partikode`) VALUES ('Venstre', 'V');